# Generated by Django 5.1.1 on 2024-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("uneducated", "Uneducated"),
                    ("primary", "Primary"),
                    ("middle", "MIDDLE"),
                    ("high", "High"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
