# Generated by Django 5.1.1 on 2024-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_date_updated_alter_customuser_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("manager", "Manager"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
    ]
