# Generated by Django 5.1.1 on 2024-10-07 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0002_initial"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="award",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="people.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="award",
            index=models.Index(
                fields=["year_awarded"], name="items_award_year_aw_d9aaf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="award",
            index=models.Index(
                fields=["author"], name="items_award_author__9210d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="award",
            index=models.Index(
                fields=["date_updated"], name="items_award_date_up_c1923e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="award",
            unique_together={("name", "year_awarded", "author")},
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="items_book_author__5faf16_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["published_date"], name="items_book_publish_dfdeae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["language"], name="items_book_languag_1dd436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["rating"], name="items_book_rating_c507ac_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["date_updated"], name="items_book_date_up_8af629_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author")},
        ),
    ]
