# Generated by Django 5.1.1 on 2024-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_award_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="view_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of times the award has been viewed on the website.",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="view_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of times the item has been viewed on the website.",
            ),
        ),
    ]
