# Generated by Django 5.1.1 on 2024-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_award_view_count_book_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Award's photograph.",
                null=True,
                upload_to="award_photos/",
            ),
        ),
        migrations.AddField(
            model_name="award",
            name="website",
            field=models.URLField(
                blank=True, help_text="Award's official website link.", null=True
            ),
        ),
    ]
