# Generated by Django 5.1.1 on 2024-10-10 19:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_award_photo_award_website"),
        ("people", "0006_alter_author_birth_date_alter_author_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-date_published"], "verbose_name_plural": "Books"},
        ),
        migrations.AlterField(
            model_name="award",
            name="author",
            field=models.ForeignKey(
                help_text="Author who received the award.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="people.author",
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this award entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photograph or logo of the award.",
                null=True,
                upload_to="award_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this award entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this award entry has been viewed."
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Link to the official website of the award.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="year_awarded",
            field=models.IntegerField(
                default=2024,
                help_text="Year the award was received.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the book.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="people.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image of the book.",
                null=True,
                upload_to="covers/",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this book entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="date_published",
            field=models.DateField(help_text="Date the book was published."),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Unique ISBN number for the book.", max_length=13, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                help_text="Language the book is written in.", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(
                help_text="Total number of pages in the book.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rating of the book (from 0 to 5).",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Brief summary of the book.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(help_text="Title of the book.", max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this book entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
