# Generated by Django 5.1.1 on 2024-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_alter_author_view_count_alter_critic_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Author's photograph.",
                null=True,
                upload_to="person_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="critic",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Author's photograph.",
                null=True,
                upload_to="person_photos/",
            ),
        ),
    ]
