# Generated by Django 5.1.1 on 2024-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_reaction_review_alter_review_critic"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="view_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of times the item has been viewed on the website.",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="view_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of times the item has been viewed on the website.",
            ),
        ),
    ]
