# Generated by Django 5.1.1 on 2024-10-10 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("people", "0006_alter_author_birth_date_alter_author_created_by_and_more"),
        ("reviews", "0004_reaction_view_count_review_view_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")],
                help_text="Reaction type: Like or Dislike.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(help_text="The comment or review content."),
        ),
        migrations.AlterField(
            model_name="review",
            name="content_type",
            field=models.ForeignKey(
                help_text="Model type being reviewed (author or book).",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="critic",
            field=models.ForeignKey(
                help_text="The critic writing the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="people.critic",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="date_starred",
            field=models.DateTimeField(
                blank=True, help_text="Date the review was starred.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="object_id",
            field=models.PositiveIntegerField(
                help_text="The ID of the object being reviewed (author or book)."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="starred",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the review is pinned at the top.",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="starred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who starred the review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="starred_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["review", "reaction_type"],
                name="reviews_rea_review__91a582_idx",
            ),
        ),
    ]
